Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "gbarbieru/xenial"
  c.vm.hostname = "default-gbarbieru-xenial"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/home/rle0427/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
  end
end
